# [START runtime]
runtime: python27
threadsafe: yes
# [END runtime]

handlers:

- url: /(.+\.(js|map|css))$
  static_files: dist/\1
  upload: dist/(.*)

# Serve index.html for (/infrastructure, /jobconfigs, and
# /jobconfigs/:configId/:runId) routes.
# TODO(b/66955251): Let the web-front end framework handles the bad routes
# instead of showing ugly App Engine 404 page.
- url: /|/infrastructure|/jobconfigs|/jobconfigs/.*
  static_files: dist/index.html
  upload: dist/index.html

# Skip files not needed for static serving
skip_files:
- ^.angular-cli.json
- ^app\.yaml
- ^e2e$
- ^karma\.config\.js
- ^node_modules$
- ^package\.json
- ^protractor\.conf\.js
- ^README.md
- ^src$
- ^tsconfig\.json
- ^tslint\.json
